global:
  scrape_interval: 15s # 預設每 15 秒拉一次

rule_files:
  - "/etc/prometheus/alert/alert_rules.yml"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] # 指向 Docker 內部的服務
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
